inherit_from:
  - .rubocop_todo.yml

Rails:
  Enabled: true

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Force before_filter until upgrade to Rails 4
Rails/ActionFilter:
  EnforcedStyle: filter

Metrics/MethodLength:
  Max: 20